<div class="slick-carousel-wrapper page-main">
    <div class="slick-carousel">
        <div class="item">
            <img src="<?php echo $this->getViewFileUrl('images/Banner.png'); ?>" alt="">
        </div>
        <div class="item">
            <img src="<?php echo $this->getViewFileUrl('images/Banner.png'); ?>" alt="">
        </div>
        <div class="item">
            <img src="<?php echo $this->getViewFileUrl('images/Banner.png'); ?>" alt="">
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
        "*": {
            "slick-carousel":{
                "element": ".slick-carousel"
            }
        }
}
</script>